#!/usr/bin/env node

const fs = require('fs');
const { argv } = require('process');

const game_id = argv[2];

const json = require(`./${game_id}.json`);

json
  .players
  .push(argv[3]);

const res = JSON.stringify(json);

fs.writeFile(`server/${game_id}.json`, res, function(err) {
    if(err) {
        return console.log(err);
    }

    console.log(res);
});
