#!/usr/bin/env node

const process = require('process');

const card = JSON.parse(decodeURIComponent(process.argv[2]));

console.log(JSON.stringify([
  { x: card.x + 1, y: card.y + 1, rotation: 1},
  { x: card.x + 1, y: card.y - 1, rotation: 3},
  { x: card.x - 1, y: card.y + 1, rotation: 2},
  { x: card.x - 1, y: card.y - 1, rotation: 4}
]));
