#!/usr/bin/env node

const process = require('process');

const { card, location } = JSON.parse(decodeURIComponent(process.argv[2]));

console.log(JSON.stringify([
  [x: 1, y: 4, orientation: 2]
]));
