#!/usr/bin/env node

const process = require('process');

#! Depenedent on Meeple impl, location referring to tile subgrid
const { player, location } = JSON.parse(decodeURIComponent(process.argv[2]));

console.log(JSON.stringify([
  [player: 1, location.x: 3, location.y: 4]
]))