#!/usr/bin/env node

const fs = require('fs');

function debounce(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		var later = function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		};
		var callNow = immediate && !timeout;
		clearTimeout(timeout);
		timeout = setTimeout(later, wait);
		if (callNow) func.apply(context, args);
	};
};

fs.watch('mock-server/sample-datastore.json', debounce((curr, prev) => {
  fs.readFile('mock-server/sample-datastore.json', 'utf8', (err, data) => {
    if (err) throw err;
    console.log(JSON.stringify(data));
  });
}, 250));
