#!/usr/bin/env sh

if [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
  java -classpath "lib/javax.json-1.0.jar;server" ApiEndpoints.JoinGame $1 $2
else
  java -classpath "lib/javax.json-1.0.jar:server" ApiEndpoints.JoinGame $1 $2
fi
