#!/usr/bin/env node

const uid = require('uid');
const fs = require('fs');

const game_id = uid(10);

const base_JSON = JSON.stringify({
  "id": game_id,
  "players": [],
  "turn": 0,
  "board": [
    {
      "x": 0,
      "y":0,
      "orientation":"NORTH",
      "name":"Single bubble city with straight road"
    }
  ]
});

fs.writeFile(`server/ApiEndpoints/${game_id}.json`, base_JSON, function(err) {
    if(err) {
        return console.log(err);
    }

    console.log(base_JSON);
});
