const Adapter = require('./index.js');

const seed = `THIS IS SPARTA!
HELLO!
WELCOME Red PLEASE WAIT FOR THE NEXT CHALLENGE
NEW CHALLENGE 1 YOU WILL PLAY 1 MATCH
BEGIN ROUND 1 OF 1
YOUR OPPONENT IS PLAYER Blue
STARTING TILE IS TLTJ- AT 0 0 0
THE REMAINING 6 TILES ARE [ TLTTP LJTJ- JLJL- JJTJX JLTTB TLLT- ]
MATCH BEGINS IN 15 SECONDS
MAKE YOUR MOVE IN GAME A WITHIN 1 SECOND: MOVE 1 PLACE TLTTP
GAME A MOVE 1 PLAYER Red PLACED TLTTP AT 0 1 90 TIGER 8
GAME B MOVE 1 PLAYER Blue PLACED TLTTP AT 0 1 90 TIGER 8
MAKE YOUR MOVE IN GAME B WITHIN 1 SECOND: MOVE 2 PLACE LJTJ
GAME A MOVE 2 PLAYER Blue PLACED LJTJ- AT 0 2 180 TIGER 8
GAME B MOVE 2 PLAYER Red PLACED LJTJ- AT 0 2 180 TIGER 8
MAKE YOUR MOVE IN GAME A WITHIN 1 SECOND: MOVE 3 PLACE JLJL
GAME A MOVE 3 PLAYER Red PLACED JLJL- AT 1 0 0 NONE
GAME B MOVE 3 PLAYER Blue PLACED JLJL- AT 1 0 0 TIGER 4
MAKE YOUR MOVE IN GAME B WITHIN 1 SECOND: MOVE 4 PLACE JJTJX
GAME A MOVE 4 PLAYER Blue PLACED JJTJX AT 1 1 270 TIGER 5
GAME B MOVE 4 PLAYER Red PLACED JJTJX AT 1 1 270 TIGER 5
MAKE YOUR MOVE IN GAME A WITHIN 1 SECOND: MOVE 5 PLACE JLTTB
GAME A MOVE 5 PLAYER Red PLACED JLTTB AT 2 0 180 TIGER 1
GAME B MOVE 5 PLAYER Blue PLACED JLTTB AT 2 0 180 TIGER 1
MAKE YOUR MOVE IN GAME B WITHIN 1 SECOND: MOVE 6 PLACE TLLT
GAME A MOVE 6 PLAYER Blue PLACED TLLT- AT 0 -1 180 CROCODILE
GAME B MOVE 6 PLAYER Red PLACED TLLT- AT 0 -1 180 TIGER 3
GAME A OVER PLAYER Red 6 PLAYER Blue 14
GAME B OVER PLAYER Red 20 PLAYER Blue 19
END OF ROUND 1 OF 1
END OF CHALLENGES
THANK YOU FOR PLAYING! GOODBYE`.split('\n');

seed
  .map(line => Adapter.parse(line))
  .forEach(msg => console.log(msg));
